### ISSUE TITLE
unexpected behavior when we update an issue or a project from a mobile phone

### ISSUE THREAD

**Issue by mathieu-mbru** [taqueci/redmine_wysiwyg_editor#141]
Hello!
We experienced a bug for iOS (iPhone)
When we update an issue or a project from a mobile phone  (case of textil mode activated) the field description will be deleted
Because the function _changeMode is called in init_instance_callback
Since the function _changeMode fire the event blur that call _setTextContent
In this case self._editor.getContent() is empty
We suggest either  delete the line 376 
![image](https://user-images.githubusercontent.com/75627140/152987851-9b9821b9-606f-4dd5-8ecd-8fdbd914ee85.png)
Or add the line 278 in the function _changeMode 
![image](https://user-images.githubusercontent.com/75627140/152987897-d9275227-a5e2-4706-b883-757b4c119754.png)

**Comment by taqueci** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

**Comment by taqueci** [comment]
Hi @mathieu-mbru 

The issue has been fixed in the latest version.
Please check in your environment.

**Comment by mathieu-mbru** [comment]
Hi
Sorry, the problem still exists when the mode textile is enabled 
![image](https://user-images.githubusercontent.com/75627140/154963617-cb8d1cfa-0751-43af-9bb6-bb71752d92fa.png)
![image](https://user-images.githubusercontent.com/75627140/154963659-1a885104-f858-4949-8aa2-67cf1da0c960.png)
![image](https://user-images.githubusercontent.com/75627140/154963681-64c7473b-3c70-4a84-9e45-0ff31d059c63.png)

**Comment by nanego** [comment]
Hello.
I can confirm, with the latest version, I still see an empty description field when I use an iPhone to edit an issue.
The applied correction may not cover all the cases.

**Comment by taqueci** [comment]
Thank you for your information.
I have created new issue #145.
